buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.67.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'gradle-failure-reports-root'

include 'gradle-failure-reports'
include 'gradle-failure-reports-exceptions'
include 'gradle-failure-reports-common'
