com.fasterxml.jackson.core:jackson-annotations = 2.20
com.netflix.nebula:nebula-test = 10.6.2
com.fasterxml.jackson.*:* = 2.20.0
org.immutables:* = 2.11.6
one.util:streamex = 0.8.4
com.palantir.gradle.auto-parallelizable:* = 1.4.0
com.google.guava:guava = 33.5.0-jre
org.apache.commons:commons-lang3 = 3.19.0
com.palantir.gradle.utils:environment-variables = 0.21.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 3.52.0

# unit testing
org.assertj:* = 3.27.6
org.junit.jupiter:* = 6.0.1
org.junit.platform:* = 6.0.1
